#version: '3.8'
services:
#MySql
  db:
    image: mysql:8.0
    container_name: real_estates_db
    restart: always
    env_file:
      - /.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real_estates_app
    restart: always
    env_file:
      - /.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: